RGB_PROMPTS = {
    "object_recognition": {
        "caption_prompt": """I am specifically focusing on visual recognition related QA type, thus can caption my input video frames paying attention to the information that is closely related to visual information, for example, scene, objects, color, texture. Please give a detailed caption that enumerate everything you can identify.""",

        "question_prompt": """Please work as a VQA assistant, treat the subject (behind the camera) in the video as I and the language model as you when generate question (ask question from human perspective). By analyzing both the video and the corresponding caption, generate questions that evaluate fine-grained understanding of visual . Please ensure comprehensive video reasoning capabilities and more challenging to be answered during a low light condition (illumination), and ask questions that more focus on perception, for example, scene, objects, rooms, buildings, color, texture, avoid questions regarding the light condition (illumination), dynamic objectsand humans exists in the video Make sure the question can be answered with a precise answer. The question doesn't need to be aligned with the frames. Please provide only 1 questions and focus on question not subjective and can be answered using few words.""",

        "answering_prompt": """Please work as a VQA assistant, treat the subject (behind the camera) in the video as I and the language model as you when generate answer (answer from human perspective). Given the frame of videos, and the questions, generate answers for each question. Please ensure the answers are consistent with the video and the questions. Make sure the answer is easy to be evaluated and not vague. Avoid answers regarding the light condition (illumination), dynamic objectsand humans exists in the video."""
    },

    "spatial_reasoning": {
        "caption_prompt": """Now, I am specifically focusing on spatial relationship between object pairs (please give more than 4 pairs). Also give the estimation of how many step between me and the object.""",

        "question_prompt": """Please work as a VQA assistant, treat the subject (behind the camera) in the video as I and the language model as you when generate question (ask question from human perspective). By analyzing both the video and the corresponding caption, generate questions that evaluate fine-grained understanding of spatial relation. Please ensure comprehensive video reasoning capabilities, and more challenging to be answered during a low light condition. Also it is good to come up with real world scenario open vocabulary questions. Avoid questions regarding the light condition (illumination), dynamic objectsand humans exists in the video. Please provide only 1 questions and focus on question not subjective and can be answered using few words.""",

        "answering_prompt": """Please work as a VQA assistant, treat the subject (behind the camera) in the video as I and the language model as you when generate answer (answer from human perspective). Given the frame of videos, and the questions, generate answers for each question. Please ensure the answers are consistent with the video and the questions. Make sure the answer is easy to be evaluated and not vague. Avoid answers regarding the light condition (illumination), dynamic objects and humans exists in the video."""
    },

    "text_recognition": {
        "caption_prompt": """Now I am focusing on text recongnition, please identify text in the video that is interesting and specify the corresponding frame number (sequence number among the input images). When you descrive the text, describe in detail and better to guess what it is used for.""",

        "question_prompt": """Please work as a VQA assistant, treat the subject (behind the camera) in the video as I and the language model as you when generate question (ask question from human perspective). By analyzing both the video and the corresponding caption, generate questions that evaluate fine-grained understanding of text recongnition. Please ensure comprehensive video reasoning capabilities, and more challenging to be answered during a low light condition. Also it is good to come up with real world scenario open vocabulary questions. Consider both text recognition (what text is shown), and text reasoning (Which office do I see the text in? How many times does the text appear? What does the text implies). Avoid questions regarding the light condition (illumination), dynamic objectsand humans exists in the video. Please provide 8 questions.""",

        "answering_prompt": """Please work as a VQA assistant, treat the subject (behind the camera) in the video as I and the language model as you when generate answer (answer from human perspective). Given the frame of videos, and the questions, generate answers for each question. Please ensure the answers are consistent with the video and the questions. Make sure the answer is easy to be evaluated and not vague. Avoid answers regarding the light condition (illumination), dynamic objects and humans exists in the video."""
    },

    "scene_sequence": {
        "caption_prompt": """I am specifically focusing on Scene Sequence, thus can caption my input video frames paying attention to the information that is closely related to sequence of object and environment passed by. Please give a detailed caption that enumerate everything you can identify""",

        "question_prompt": """Please work as a VQA assistant, treat the subject (behind the camera) in the video as I and the language model as you when generate question (ask question from human perspective). By analyzing both the video and the corresponding caption, generate questions that evaluate finegrained understanding of scene sequence. Avoid questions that can be answered from a few frames; instead, design questions that require understanding the entire video, ensuring comprehensive video reasoning capabilities, and more challenging to be answered during a low light condition (illumination). Ask questions that more focus on scene sequence, for example What’s the sequence of scenes I just passed? What did I pass before the kitchen? Which room connects the living room and the kitchen? Make sure the question can be answered with a precise answer. The question doesn't need to be aligned with the frames. Avoid questions regarding the light condition (illumination), dynamic objectsand humans exists in the video. Please provide 10 questions.""",

        "answering_prompt": """Please work as a VQA assistant, treat the subject (behind the camera) in the video as I and the language model as you when generate answer (answer from human perspective). Given the frame of videos, and the questions, generate answers for each question. Please ensure the answers are consistent with the video and the questions. Make sure the answer is easy to be evaluated and not vague. Avoid answers regarding the light condition (illumination), dynamic objects and humans exists in the video."""
    },

    "light_recongnition": {
        "caption_prompt": """I am specifically focusing on light source recognition related QA type, thus can caption my input video frames paying attention to the information that is closely related to light information. Please give a detailed caption that enumerate everything you can identify""",

        "question_prompt": """Please work as a VQA assistant, treat the subject (behind the camera) in the video as I and the language model as you when generate question (ask question from human perspective). By analyzing both the video and the corresponding caption, generate questions that evaluate fine-grained understanding of Light attribute. Please ensure comprehensive video reasoning capabilities and more challenging to be answered during a low light condition (illumination), and ask questions that more focus on illumination, for example, light Source type, direction, color, number, shape or strength, avoid questions regarding dynamic objects and humans exists in the video Make sure the question can be answered with a precise answer. The question doesn't need to be aligned with the frames. Please provide only 1 questions and focus on question not subjective and can be answered using few words.""",

        "answering_prompt": """Please work as a VQA assistant, treat the subject (behind the camera) in the video as I and the language model as you when generate answer (answer from human perspective). Given the frame of videos, and the questions, generate answers for each question. Please ensure the answers are consistent with the video and the questions. Make sure the answer is easy to be evaluated and not vague. Avoid answers regarding dynamic objects and humans exists in the video."""
    },

    "light_change": {
        "caption_prompt": """I am specifically focusing on light changing among the video, thus can caption my input video frames paying attention to the information that is closely related to light information. Please give a detailed caption that enumerate everything you can identify""",

        "question_prompt": """Please work as a VQA assistant, treat the subject (behind the camera) in the video as I and the language model as you when generate question (ask question from human perspective). By analyzing both the video and the corresponding caption, generate questions that evaluate fine-grained understanding of Light changing. Please avoid questions that can be answered from a few frames and ensure comprehensive video reasoning capabilities and more challenging to be answered during a low light condition (illumination), and ask questions that more focus on illumination, for example, “Did the lights turn on/off?” “Is it getting darker/brighter? “Is the light approaching me?” “Did a car’s headlights just pass by? Please provide 8 questions.""",

        "answering_prompt": """Please work as a VQA assistant, treat the subject (behind the camera) in the video as I and the language model as you when generate answer (answer from human perspective). Given the frame of videos, and the questions, generate answers for each question. Please ensure the answers are consistent with the video and the questions. Make sure the answer is easy to be evaluated and not vague. Avoid answers regarding dynamic objects and humans exists in the video."""
    },

    "counting": {
        "caption_prompt": """Now I am focusing on counting question, please identify more than 5 interesting object which is useful during daily life and count the existence number of the object in the full video sequence.""",

        "question_prompt": """Please work as a VQA assistant, treat the subject (behind the camera) in the video as I and the language model as you when generate question (ask question from human perspective). By analyzing both the video and the corresponding caption, generate questions that evaluate fine-grained understanding of counting. Avoid questions that can be answered from a few frames; instead, design questions that require understanding the entire video, ensuring comprehensive video reasoning capabilities, and more challenging to be answered during a low light condition. Ask questions that more focus on counting, for example object, room, buildings etc. Make sure the question can be answered with a precise answer. The question doesn't need to be aligned with the frames. Avoid questions regarding the light condition (illumination), dynamic objectsand humans exists in the video. Please provide 10 questions.""",

        "answering_prompt": """Please work as a VQA assistant, treat the subject (behind the camera) in the video as I and the language model as you when generate answer (answer from human perspective). Given the frame of videos, and the questions, generate answers for each question. Please ensure the answers are consistent with the video and the questions. Make sure the answer is easy to be evaluated and not vague. Avoid answers regarding the light condition (illumination), dynamic objects and humans exists in the video."""
    },

    "dynamic_counting": {
        "caption_prompt": """I am specifically focusing on counting dynamic human or objects among the video, thus can caption my input video frames paying attention to the information that is closely related to anything moving except the subject. Please give a detailed caption that enumerate everything you can identify""",

        "question_prompt": """Please work as a VQA assistant, treat the subject (behind the camera) in the video as I and the language model as you when generate question (ask question from human perspective). By analyzing both the video and the corresponding caption, generate questions that evaluate finegrained understanding of counting dynamic object or human. Please avoid questions that can be answered from a few frames and ensure comprehensive video reasoning capabilities and more challenging to be answered during a low light condition (illumination), and ask questions that more focus on the current moving object but not include me (person holding the camera). For examples: How many cars approach me? Please avoid question regarding illumination. Please provide 8 questions.""",

        "answering_prompt": """Please work as a VQA assistant, treat the subject (behind the camera) in the video as I and the language model as you when generate answer (answer from human perspective). Given the frame of videos, and the questions, generate answers for each question. Please ensure the answers are consistent with the video and the questions. Make sure the answer is easy to be evaluated and not vague. Please avoid answer regarding illumination."""
    },

    "non_common": {
        "caption_prompt": """Now, I am specifically focusing on non-common sense reasoning, which means you should find all the wierd things violate common sense or physical law in the given video and give an improvement suggestion for that. Only focus on the layout design (the furniture or object shouldn't be there), or simulator related drawback (something looks unrealistic, or there are some mesh clipping, object floating etc.)""",

        "question_prompt": """Please work as a VQA assistant, treat the subject (behind the camera) in the video as I and the language model as you when generate question (ask question from human perspective). By analyzing both the video and the corresponding caption, generate questions that evaluate fine-grained understanding of the non-common wierd or wrong scenario. Please ensure comprehensive video reasoning capabilities, and more challenging to be answered during a low light condition. Only consider questions that is presenting in the video and don't ask anything that cannot be observed in the video, avoid questions regarding the light condition (illumination), dynamic objectsand humans exists in the video. Only focus on the layout design (the furniture or object shouldn't be there), or simulator related drawback (something looks unrealistic, or there are some mesh clipping, object floating etc.)""",

        "answering_prompt": """Please work as a VQA assistant, treat the subject (behind the camera) in the video as I and the language model as you when generate answer (answer from human perspective). Given the frame of videos, and the questions, generate answers for each question. Please ensure the answers are consistent with the video and the questions. Make sure the answer is easy to be evaluated and not vague. Avoid answers regarding the light condition (illumination), dynamic objects and humans exists in the video."""
    },

    "navigation": {
        "caption_prompt": """I am specifically focusing on navigation, thus can caption my input video frames paying attention to the information that is closely related to actions such as turn left turn right and how many steps for each action. Please give a detailed caption that enumerate everything you can identify""",

        "question_prompt": """Please work as a VQA assistant, treat the subject (behind the camera) in the video as I and the language model as you when generate question (ask question from human perspective). By analyzing both the video and the corresponding caption, generate questions that evaluate fine-grained understanding of navigation. Generate QA pairs regarding navigation, for example, Which way should I go to reach the kitchen? What’s the fastest way back to the living room? How do I get to the bus stop from here? Avoid questions that can be answered from a few frames; instead, design questions that require understanding the entire video, ensuring comprehensive video reasoning capabilities, and more challenging to be answered during a low light condition (illumination). Make sure the question can be answered with a precise answer. The question doesn't need to be aligned with the frames. Avoid questions regarding the light condition (illumination), dynamic objects, and humans exists in the video. Please provide 10 questions.""",

        "answering_prompt": """Please work as a VQA assistant, treat the subject (behind the camera) in the video as I and the language model as you when generate answer (answer from human perspective). Given the frame of videos, and the questions, generate answers for each question. Please ensure the answers are consistent with the video and the questions. Make sure the answer is easy to be evaluated and not vague. Avoid answers regarding the light condition (illumination), dynamic objects and humans exists in the video."""
    },

    "dynamic_recognition": {
        "caption_prompt": """I am specifically focusing on dynamic human or objects among the video, thus can caption my input video frames paying attention to the information that is closely related to anything moving except the subject. Please give a detailed caption that enumerate everything you can identify, and add the start and end frame of the dynamic object or human.""",

        "question_prompt": """Please work as a VQA assistant, treat the subject (behind the camera) in the video as I and the language model as you when generate question (ask question from human perspective). By analyzing both the video and the corresponding caption, generate questions that evaluate fine-grained understanding of dynamic object or human. Please avoid questions that can be answered from a few frames and ensure comprehensive video reasoning capabilities and more challenging to be answered during a low light condition (illumination), and ask questions that more focus on the current moving object but not include me (person holding the camera). Also it is good to come up with real world scenario open vocabulary questions. For examples: Did a new object appear?” Did a car approach me? Has the door fully closed? Has the bus departed? Did a person walk to me? When? Time duration where? Please avoid question regarding illumination.""",

        "answering_prompt": """Please work as a VQA assistant, treat the subject (behind the camera) in the video as I and the language model as you when generate answer (answer from human perspective). Given the frame of videos, and the questions, generate answers for each question. Please ensure the answers are consistent with the video and the questions. Make sure the answer is easy to be evaluated and not vague. Please avoid answer regarding illumination."""
    },

    "action": {
        "caption_prompt": """Now, I am specifically focusing on action of the subject (behind camera). Please give detailed explaination of the action conducted, object interacted, as well as the possible purpose and consequence.""",

        "question_prompt": """Please work as a VQA assistant, treat the subject (behind the camera) in the video as I and the language model as you when generate question (ask question from human perspective). By analyzing both the video and the corresponding caption, generate questions that evaluate finegrained understanding of my action. Please ensure comprehensive video reasoning capabilities, and more challenging to be answered during a low light condition. Also it is good to come up with real world scenario open vocabulary questions. Avoid questions regarding the light condition (illumination), dynamic objectsand humans exists in the video. Please provide 8 questions.""",

        "answering_prompt": """Please work as a VQA assistant, treat the subject (behind the camera) in the video as I and the language model as you when generate answer (answer from human perspective). Given the frame of videos, and the questions, generate answers for each question. Please ensure the answers are consistent with the video and the questions. Make sure the answer is easy to be evaluated and not vague. Avoid answers regarding the light condition (illumination), dynamic objects and humans exists in the video"""
    }
}