"""Stable menu choices for aligned QA registry actions."""

ALIGNED_RGB_TEST = "37"
ALIGNED_RGB_RUN = "38"
ALIGNED_RGB_REPAIR = "38r"

ALIGNED_EVENT_TEST = "39"
ALIGNED_EVENT_RUN = "40"
ALIGNED_EVENT_REPAIR = "40r"

ALIGNED_IR_TEST = "41"
ALIGNED_IR_RUN = "42"
ALIGNED_IR_REPAIR = "42r"

ALIGNED_MARIGOLD_RUN = "47"
ALIGNED_MARIGOLD_ESTIMATE = "47e"
ALIGNED_MARIGOLD_QA = "47q"
ALIGNED_MARIGOLD_REPAIR = "47r"

ALIGNED_QA_QUALITY_EVALUATE = "64"
ALIGNED_QA_QUALITY_LLM_EVAL = "65"

REGISTERED_MENU_CHOICE_ORDER = (
    ALIGNED_RGB_TEST,
    ALIGNED_RGB_RUN,
    ALIGNED_RGB_REPAIR,
    ALIGNED_EVENT_TEST,
    ALIGNED_EVENT_RUN,
    ALIGNED_EVENT_REPAIR,
    ALIGNED_IR_TEST,
    ALIGNED_IR_RUN,
    ALIGNED_IR_REPAIR,
    ALIGNED_MARIGOLD_RUN,
    ALIGNED_MARIGOLD_ESTIMATE,
    ALIGNED_MARIGOLD_QA,
    ALIGNED_MARIGOLD_REPAIR,
    ALIGNED_QA_QUALITY_EVALUATE,
    ALIGNED_QA_QUALITY_LLM_EVAL,
)

REGISTERED_MENU_SECTION_ORDER = (
    "ALIGNED RGB PIPELINE",
    "ALIGNED EVENT PIPELINE",
    "ALIGNED IR PIPELINE",
    "ALIGNED MARIGOLD DEPTH PIPELINE",
    "ALIGNED QA QUALITY",
)
